"""empty message

<<<<<<< HEAD:migrations/versions/80a92a6191b6_.py
Revision ID: 80a92a6191b6
Revises: 
Create Date: 2020-11-22 20:41:01.116065
=======
Revision ID: b64ef8b0e669
Revises: 
Create Date: 2020-11-21 23:42:35.820582
>>>>>>> 30e3fc461936bf628403f4b32d2fbf4b549364b8:migrations/versions/b64ef8b0e669_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD:migrations/versions/80a92a6191b6_.py
revision = '80a92a6191b6'
=======
revision = 'b64ef8b0e669'
>>>>>>> 30e3fc461936bf628403f4b32d2fbf4b549364b8:migrations/versions/b64ef8b0e669_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Reservation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('people_number', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Reservation')
    # ### end Alembic commands ###
